### ISSUE TITLE
Cannot find module 'react/lib/ReactInstanceHandles'

### ISSUE THREAD

**Issue by konsumer** [Yomguithereal/react-blessed#55]
I get this error with this demo code:

```js
import React from 'react'
import blessed from 'blessed'
import { render } from 'react-blessed'

export const App = () => (
  <box label='react-blessed demo'
       border={{type: 'line'}}
       style={{border: {fg: 'cyan'}}}>
    Random text here...
  </box>
)

const screen = blessed.screen({
  autoPadding: true,
  smartCSR: true,
  title: 'react-blessed demo app'
})
screen.key(['escape', 'q', 'C-c'], (ch, key) => process.exit(0))

render(<App />, screen)
```

I think it might be related to [this issue](https://github.com/facebook/react/issues/8342)

The Full error follows:
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactInstanceHandles'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/konsumer/WORK/quest/node_modules/react-blessed/dist/render.js:15:37)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/konsumer/WORK/quest/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! quest@1.0.0 start: `babel-node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quest@1.0.0 start script 'babel-node src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/konsumer/WORK/quest/npm-debug.log
```

**Comment by konsumer** [comment]
Seems to work fine with these versions locked in:

```
{
"dependencies": {
    "blessed": "^0.1.81",
    "react": "^0.14.0",
    "react-blessed": "^0.1.7",
  }
}
```

**Comment by Yomguithereal** [comment]
Hello @konsumer. Yes, I think the library does not work with React v15. I'll change that when I have some time but since the internals of React change quite quickly, it's difficult to make the contraption stable.

**Comment by konsumer** [comment]
No prob! I totally understand. Maybe some code generation would help? I'd be happy to take a look when I have time.

**Comment by Yomguithereal** [comment]
I don't think code generation would help. However, finding what changed regarding dependency injection between React 0.14 & 15 and bootstrapping the library conditionally to react's version would be awesome.

**Comment by konsumer** [comment]
Ah yes, I investigated how you are doing stuff now, and it's pretty dynamic. I will look into it more.

**Comment by neurosnap** [comment]
Any updates on this?
