### ISSUE TITLE
Error: Cannot find module 'react/lib/ReactInstanceHandles' @ React v16

### ISSUE THREAD

**Issue by Lokeh** [Yomguithereal/react-blessed#70]
My dependencies:
```
  "dependencies": {
    "blessed": "^0.1.81",
    "react": "^16.2.0",
    "react-blessed": "^0.2.0",
    "reason-react": "^0.3.0"
  },
```

My test code:

```javascript
import React, {Component} from 'react';
import blessed from 'blessed';
import {render} from 'react-blessed';

// Rendering a simple centered box
class App extends Component {
  render() {
    return (
      <box top="center"
           left="center"
           width="50%"
           height="50%"
           border={{type: 'line'}}
           style={{border: {fg: 'blue'}}}>
        Hello World!
      </box>
    );
  }
}

// Creating our screen
const screen = blessed.screen({
  autoPadding: true,
  smartCSR: true,
  title: 'react-blessed hello world'
});

// Adding a way to quit the program
screen.key(['escape', 'q', 'C-c'], function(ch, key) {
  return process.exit(0);
});

// Rendering the React app using our screen
const component = render(<App />, screen);
```

Output:

```
> node test.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactInstanceHandles'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/r627543/Code/repohunter/node_modules/react-blessed/dist/render.js:8:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)```

**Comment by Lokeh** [comment]
OK, I've been able to get past this error. `dist/` on NPM and `package.json` are stale. Steps to fix:

1. Clone the repo
2. Do a full clean build
3. Change `package.json` to:
```
{
...
  "main": "./dist/index.js",
...
}```

**Comment by Lokeh** [comment]
However, I now have a new error: when I try and run the test file above, I get the error:

```
The above error occurred in one of your React components:
    in box
    in InnerBox
    in box
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
Error: No active screen.
    at Text.Node (/Users/r627543/Code/react-blessed/node_modules/blessed/lib/widgets/node.js:57:13)
    at Text.Element (/Users/r627543/Code/react-blessed/node_modules/blessed/lib/widgets/element.js:49:8)
    at new Text (/Users/r627543/Code/react-blessed/node_modules/blessed/lib/widgets/text.js:24:11)
    at Function.Text (/Users/r627543/Code/react-blessed/node_modules/blessed/lib/widgets/text.js:20:12)
    at createTextInstance (/Users/r627543/Code/react-blessed/dist/fiber/fiber.js:77:20)
    at completeWork (/Users/r627543/Code/react-blessed/node_modules/react-reconciler/cjs/react-reconciler.development.js:4469:42)
    at completeUnitOfWork (/Users/r627543/Code/react-blessed/node_modules/react-reconciler/cjs/react-reconciler.development.js:5918:18)
    at performUnitOfWork (/Users/r627543/Code/react-blessed/node_modules/react-reconciler/cjs/react-reconciler.development.js:6020:14)
    at workLoop (/Users/r627543/Code/react-blessed/node_modules/react-reconciler/cjs/react-reconciler.development.js:6074:26)
    at Object.invokeGuardedCallback$1 (/Users/r627543/Code/react-blessed/node_modules/react-reconciler/cjs/react-reconciler.development.js:1562:10)
```

Using `blessed` directly works fine. When I run the examples in this repo, they work. I'm not sure what's going on. Should I create a new issue?

**Comment by Lokeh** [comment]
I deleted my last comment - it seems that it wasn't working properly when using `npm link`. By doing the above steps inside of `node_modules`, it works correctly

**Comment by Yomguithereal** [comment]
@Lokeh is this matter resolved then? Should I close?

**Comment by Lokeh** [comment]
@Yomguithereal not at all. Installing from NPM is still broken unless the user does the above three steps inside of `node_modules`.

You need to:

1. Fix package.json to correctly point `"main"` to `"./dist/index.js"`
2. *Fully delete* `dist/` and rebuild before publishing to NPM

**Comment by Yomguithereal** [comment]
Fair enough. I've published a fix on npm. Can you tell me if it's good now?

**Comment by Lokeh** [comment]
👍
